//
// IllumiSurf-XPanel.h
//

#include "illumisurf.h"

enum IllumiSurf_XPanelIDs {
  ISX_BLEND_MODE      = 0x8000,
  ISX_BASE_INTENSITY,
  ISX_ALT_INTENSITY,
  ISX_USE_COLOR,
  ISX_COLOR,
  ISX_USE_LUMINOSITY,
  ISX_LUMINOSITY,
  ISX_USE_DIFFUSION,
  ISX_DIFFUSION,
  ISX_USE_SPECULAR,
  ISX_SPECULAR,
  ISX_USE_GLOSSINESS,
  ISX_GLOSSINESS,
  ISX_USE_REFLECTION,
  ISX_REFLECTION,
  ISX_USE_TRANSPARENCY,
  ISX_TRANSPARENCY,
  ISX_USE_REFRACTION,
  ISX_REFRACTION,
  ISX_USE_TRANSLUCENCY,
  ISX_TRANSLUCENCY,

  ISX_BLEND_GROUP,
  ISX_INTENSITY_GROUP,
  ISX_VALUES_GROUP1,
  ISX_VALUES_GROUP2,
  ISX_VALUES_GROUP3,
};

extern LWXPanelControl  main_controls[];
extern LWXPanelDataDesc main_data[];
extern LWXPanelHint     main_hint[];

